// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"nft/hertz_demo/config"
)

func main() {
	h := server.Default()
	config.InitDB()
	register(h)
	h.Spin()
}
