// Code generated by hertz generator.

package VirtualGallery

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nfthomepageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nftmarketspaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nftmytabMw() []app.HandlerFunc {
	// your code...
	return nil
}
